enum AddressDeleteReasonType {
  NO_LONGER_WANTS_TO_BE_RELEASED_HERE = 'NO_LONGER_WANTS_TO_BE_RELEASED_HERE',
  NOT_ENOUGH_TIME_TO_ASSESS = 'NOT_ENOUGH_TIME_TO_ASSESS',
  HAS_ANOTHER_SUITABLE_ADDRESS = 'HAS_ANOTHER_SUITABLE_ADDRESS',
  OTHER_REASON = 'OTHER_REASON',
}
export default AddressDeleteReasonType
