enum AssessmentStatus {
  NOT_STARTED = 'NOT_STARTED',
  ELIGIBILITY_AND_SUITABILITY_IN_PROGRESS = 'ELIGIBILITY_AND_SUITABILITY_IN_PROGRESS',
  ELIGIBLE_AND_SUITABLE = 'ELIGIBLE_AND_SUITABLE',
  AWAITING_ADDRESS_AND_RISK_CHECKS = 'AWAITING_ADDRESS_AND_RISK_CHECKS',
  ADDRESS_AND_RISK_CHECKS_IN_PROGRESS = 'ADDRESS_AND_RISK_CHECKS_IN_PROGRESS',
  AWAITING_PRE_DECISION_CHECKS = 'AWAITING_PRE_DECISION_CHECKS',
  AWAITING_DECISION = 'AWAITING_DECISION',
  APPROVED = 'APPROVED',
  AWAITING_PRE_RELEASE_CHECKS = 'AWAITING_PRE_RELEASE_CHECKS',
  PASSED_PRE_RELEASE_CHECKS = 'PASSED_PRE_RELEASE_CHECKS',
  ADDRESS_UNSUITABLE = 'ADDRESS_UNSUITABLE',
  AWAITING_REFUSAL = 'AWAITING_REFUSAL',
  INELIGIBLE_OR_UNSUITABLE = 'INELIGIBLE_OR_UNSUITABLE',
  REFUSED = 'REFUSED',
  TIMED_OUT = 'TIMED_OUT',
  POSTPONED = 'POSTPONED',
  OPTED_OUT = 'OPTED_OUT',
  RELEASED_ON_HDC = 'RELEASED_ON_HDC',
}

export default AssessmentStatus
