enum AuthRole {
  CASE_ADMIN = 'ROLE_LICENCE_CA',
  RESPONSIBLE_OFFICER = 'ROLE_LICENCE_RO',
  DECISION_MAKER = 'ROLE_LICENCE_DM',
  READONLY = 'ROLE_LICENCE_READONLY',
  ASSISTANT_CHIEF = 'ROLE_LICENCE_ACO',
  SUPPORT = 'ROLE_NOMIS_BATCHLOAD',
}

export default AuthRole
