---
# Per environment values which override defaults in hmpps-assess-for-early-release-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: assess-for-early-release-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://assess-for-early-release-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    DPS_URL: 'https://dps-dev.prison.service.justice.gov.uk'
    HMPPS_COMPONENT_API_URL: 'https://frontend-components-dev.hmpps.service.justice.gov.uk'

generic-prometheus-alerts:
  alertSeverity: 